name = "mcp-workshop"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]

# Rate limiting KV store
# Create with: wrangler kv namespace create RATE_LIMIT
# Then paste the id below.
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "5b498575cbf54a0ab96e7082a3ebfa65"

# Tool requests KV store
# Create with: wrangler kv namespace create TOOL_REQUESTS
# Then paste the id below
[[kv_namespaces]]
binding = "TOOL_REQUESTS"
id = "502ed6faf3e649f0a372d458eac51f99"